### ISSUE TITLE
No link to this repository from external documentation site

### ISSUE THREAD

**Issue by tinchoabbate** [OpenZeppelin/openzeppelin-subgraphs#11]
While going over https://docs.openzeppelin.com/subgraphs/0.1.x, I noticed there's no reference that links back to this repository. So I couldn't easily figure out that this is the repository where we keep the actual code that I should use to follow the docs.

What do you think of adding a link to this repository in the main page at https://docs.openzeppelin.com/subgraphs/0.1.x/ ?

**Comment by frangio** [comment]
Good point, thanks! Fixed in https://github.com/OpenZeppelin/openzeppelin-subgraphs/commit/e8c915eae63fdbf51cae1c7181f3e16a856d9a7b.
