### ISSUE TITLE
Error during codegen

### ISSUE THREAD

**Issue by amrap030** [OpenZeppelin/openzeppelin-subgraphs#20]
Hello together,

i am receiving the following error on `codegen`:

<img width="1579" alt="Bildschirmfoto 2022-03-23 um 13 32 33" src="https://user-images.githubusercontent.com/35061229/159700106-2f0f67de-aab0-4715-9c61-483e21cb9632.png">

The code is available in https://github.com/amrap030/subgraph

Node version: v14.17.0
Npm version: 6.14.13

I would be glad if you can have a look at it. Thank you in advance!

**Comment by Amxx** [comment]
Hello @amrap030 

The error happens when running `graph-cli`. [This is a graphprotocol package](https://github.com/graphprotocol/graph-cli). You may want to check there. What version are you using? To me, it looks like a dependency issue.

**Comment by Amxx** [comment]
Unfortunately, it did happen in the past that new versions of the graph-cli were broken. Can you please try with
```
"@graphprotocol/graph-cli": "^0.26.0",
"@graphprotocol/graph-ts": "^0.24.1",
```
