### ISSUE TITLE
gitignore and generated/

### ISSUE THREAD

**Issue by the-emerald** [OpenZeppelin/openzeppelin-subgraphs#24]
Hey there! I've been doing some hacking related to adding new custom modules for my contracts, and noticed this. Most of the f`*.schema.graphql` file for each module are explicitly tracked per the `.gitignore`, with the exception of `erc1967upgrade`. Is there a particular reason for this? I see that on `npm i` and publishing that these files, alongside the `yaml` files are re-generated from source anyways.

**Comment by Amxx** [comment]
The reason why they are not ignored, despite being regenerate by `npm prepare`, is to track changes to the produced schema in git. These changes would possibly be breaking the graphql interface that user rely on.

I'm adding the missing modules that were forgotten.
