### ISSUE TITLE
Issue of using Bytes as entity IDs

### ISSUE THREAD

**Issue by haowang1013** [OpenZeppelin/openzeppelin-subgraphs#26]
Hi,

It seems right now there's a problem of using Bytes as IDs with the graph node, I've filed an issue [here](https://github.com/graphprotocol/graph-node/issues/3600).

I don't think this is a problem of openzeppelin-subgraphs but I'm curious if anyone is seeing similar problems.

Also, I'm curious why one might favor using `Bytes` as opposed to `ID` when representing addresses, better performance?

**Comment by frangio** [comment]
Yes, using `Bytes` is the new recommendation for performance. See [this article](https://medium.com/edge-node-engineering/two-simple-subgraph-performance-improvements-a76c6b3e7eac).

**Comment by Amxx** [comment]
I discovered this issue independently and then realized you had already opened an issue. I added a disclaimer in the readme

**Comment by the-emerald** [comment]
https://github.com/graphprotocol/graph-node/issues/3600 has been fixed!
