### ISSUE TITLE
Problem during compilation

### ISSUE THREAD

**Issue by marceljay** [OpenZeppelin/openzeppelin-subgraphs#3]
When I attempt to compile with `npx graph-compiler` I get the following error in regard to the first entry in the `datasources` array in the sample.json. However, the .gql.json files exist in that directory. 

```
Cannot find module 'erc721.gql.json'
Require stack:
- /home/maverick/Code/eth/openzeppelin-subgraphs/node_modules/@amxx/graphprotocol-utils/scripts/graph-compiler/config.js
- /home/maverick/Code/eth/openzeppelin-subgraphs/node_modules/@amxx/graphprotocol-utils/scripts/graph-compiler/cli.js
```

npx: 6.14.13
Ubuntu 20.04

**Comment by dabit3** [comment]
Try installing `@openzeppelin/subgraphs`:

```sh
npm install @openzeppelin/subgraphs
```

Then running again

**Comment by Amxx** [comment]
You might be trying to compile a config without the `--include` flag.

Please have a look at the `scripts/deploy.sh` script.

**Comment by freeatnet** [comment]
Side-note: if you're yarn workspaces (like (scaffold-eth)[https://github.com/austintgriffith/scaffold-eth/] does), you may need to adjust the `nohoist` directive in the root `package.json` file. Otherwise, the `--include` path won't match.

**Comment by marceljay** [comment]
> Try installing `@openzeppelin/subgraphs`:
> 
> ```shell
> npm install @openzeppelin/subgraphs
> ```
> 
> Then running again

I was running the command in this raw repository, I guess it's supposed to be executed only when it's a dependency?

**Comment by marceljay** [comment]
I ran this command in the raw repository:
```
npx graph-compiler \                
  --config configs/sample.json \
  --include node_modules/@openzeppelin/subgraphs/src/datasources \
  --export-schema \
  --export-subgraph
```

**Comment by Amxx** [comment]
Hello @marceljay 

This repo is designed to be "included" by doing `npm install @openzeppelin/subgraphs` in your working directory. If you do so, then the command you wrote should work.

If you use git clone instead, you'll need to run `npm run prepare` yourself, and change the include path to point to `./src/datasources`
