### ISSUE TITLE
Duplicate key value violates unique constraint after #25

### ISSUE THREAD

**Issue by ernestognw** [OpenZeppelin/openzeppelin-subgraphs#34]
## Description
After #25, some entities were moved to `immutable: true`, which is reasonable and shouldn't be a problem. However, there are some entities that are being saved twice (with the same data), so there was no issue previous to the migration to immutable, but now it flags them as duplicated.

Overall, this issue is not happening to all of the immutable entities, but here are some examples

<img width="880" alt="Captura de Pantalla 2022-06-19 a la(s) 4 46 42" src="https://user-images.githubusercontent.com/33379285/174631811-6d82af7e-b2b9-4db4-bf6d-d4368485af4a.png">
<img width="929" alt="Captura de Pantalla 2022-06-19 a la(s) 8 05 00" src="https://user-images.githubusercontent.com/33379285/174631818-e4d2bc86-f186-48ff-a1b4-4687cd5fff65.png">

## Proposed solution
Just check that any immutable entity that already exists doesn't get saved again.

**Comment by Amxx** [comment]
> However, there are some entities that are being saved twice (with the same data), so there was no issue previous to the migration to immutable, but now it flags them as duplicated.

Is that true? AFAIK, pushing the same entry with the same data twice was not a problem

**Comment by Amxx** [comment]
(closed by mistake)

**Comment by Amxx** [comment]
can you point to a subgraph instance that fails because of that ?

**Comment by Amxx** [comment]
I managed to replicate the issue. F***

**Comment by Amxx** [comment]
It apparently doesn't happen for ERC1155. Any reason why ?

**Comment by Amxx** [comment]
Also, with access control, it apparently isn't consistent. I tried indexing a contract I know, and I had no `role_id_key` issues

**Comment by ernestognw** [comment]
> can you point to a subgraph instance that fails because of that ?

I can deploy one, but it'll take some time, and with the fix I sent, every subgraph that I deployed with [these scripts](https://github.com/ernestognw/access-control-subgraphs) worked, so I think that's consistent.

However, I have a concrete example of how it's failing:

1. The Access Control subgraph for Rinkeby always failed on [this block](https://rinkeby.etherscan.io/txs?block=6757134)
2. Taking a look at that, you can see there are two transactions creating contracts and emitting the `RoleGranted` event. [This one](https://rinkeby.etherscan.io/tx/0x857eb85031842d497d1659d207332351bd6f3ebb4976663ae3c0178621a526ec) and [this one](https://rinkeby.etherscan.io/tx/0x6087c7785fcf7f8450879ea8485c663965f2e2878c72aa52f259afa2cb60c004).
3. This block was creating the duplicated `role_id_key` problem because it was [creating an entry with the same role id](https://github.com/OpenZeppelin/openzeppelin-subgraphs/blob/main/src/fetch/accesscontrol.ts#L21)

I can redeploy the failing subgraph to Rinkeby so you can take a look if needed.

**Comment by Amxx** [comment]
Thanks for these pointers

**Comment by Amxx** [comment]
> This block was creating the duplicated `role_id_key` problem because it was [creating an entry with the same role id](https://github.com/OpenZeppelin/openzeppelin-subgraphs/blob/main/src/fetch/accesscontrol.ts#L21)

But then, any subgraph where the same role is granted multiple times (or granted then removed), should fail because of [this line](https://github.com/OpenZeppelin/openzeppelin-subgraphs/blob/main/src/datasources/accesscontrol.ts#L53) ... expect that doesn't happen.

**Comment by Amxx** [comment]
I started syncing a subgraph that indexes all `accesscontrol` on rinkeby starting at block `6757133`, and it indexes the two contracts you identified :/

**Comment by ernestognw** [comment]
> But then, any subgraph where the same role is granted multiple times (or granted then removed), should fail because of [this line](https://github.com/OpenZeppelin/openzeppelin-subgraphs/blob/main/src/datasources/accesscontrol.ts#L53) ... expect that doesn't happen.

I didn't find any other deployed subgraph using the most recent `immutable: true` change, so although it's happening, there were no examples I guess.

> I started syncing a subgraph that indexes all `accesscontrol` on rinkeby starting at block `6757133`, and it indexes the two contracts you identified :/
> 
> Edit: and then it fails at 6931053

Yeah, if you start on the block I said seems like it doesn't fail because the collision happens with a block that's before.
I re-deployed the Rinkeby one here: https://thegraph.com/hosted-service/subgraph/ernestognw/access-control-rinkeby?version=pending but it's from block 0 and it's the only consistent way I know of making it fail.

**Comment by Amxx** [comment]
I wonder what that fails, but indexing a single contract (such as "0x41545f8b9472D758bB669ed8EaEEEcD7a9C4Ec29" on mainnet) does not cause the same error.

I got this answer

> So for what I know, you can save an immutable entity multiple times in the block that creates it. It is only sealed after the block is fully processed. 

But the instance above loads recreates the Role entity every time the role is granted on some contract, which did happen with 6000 blocks between events.

**Comment by ernestognw** [comment]
> I wonder what that fails, but indexing a single contract (such as "0x41545f8b9472D758bB669ed8EaEEEcD7a9C4Ec29" on mainnet) does not cause the same error.
> 
> I got this answer
> 
> > So for what I know, you can save an immutable entity multiple times in the block that creates it. It is only sealed after the block is fully processed.

Yeah, that's what I thought. If that's the case, but we still don't want to add a lot of `.load`, we should identify which entities are prone to this kind of error and guard it with a `.load`

> But the instance above loads recreates the Role entity every time the role is granted on some contract, which did happen with 6000 blocks between events.

So `fetchRole` was called many times in between the contract creation and the error? WAS!?

**Comment by Amxx** [comment]
> > But the instance above loads recreates the Role entity every time the role is granted on some contract, which did happen with 6000 blocks between events.
> 
> So `fetchRole` was called many times in between the contract creation and the error? WAS!?

There is not even an error on this subgraph.
