### ISSUE TITLE
Cannot access derived fields of ERC-721

### ISSUE THREAD

**Issue by the-emerald** [OpenZeppelin/openzeppelin-subgraphs#40]
Attempting to access any derived fields inside functions will result in failure.
```
Subgraph instance failed to run: Mapping aborted at ../node_modules/@openzeppelin/subgraphs/generated/schema.ts, line 2426, column 12, with message: unexpected null wasm backtrace: 0: 0x3f30 - <unknown>!../node_modules/@openzeppelin/subgraphs/src/datasources/erc721/handleTransfer in handler `handleTransfer` at block #14456901 (cd04b81af2bf4c1057c5455097d0b2cdd5b7a3601ab1834316175d07f0c05843), code: SubgraphSyncingFailure
```

This does not only happen with `contract.tokens`, but with all other derived fields in ERC-721 too.

Reproduction:
https://github.com/the-emerald/oz-subgraph-tokens

```
npm i
```
and then go to `node_modules/@openzeppelin/subgraphs/src/datasources/erc721.ts`, in `handleTransfer`:
```diff
export function handleTransfer(event: TransferEvent): void {
	let contract = fetchERC721(event.address)
	if (contract != null) {
		let token = fetchERC721Token(contract, event.params.tokenId)
		let from  = fetchAccount(event.params.from)
		let to    = fetchAccount(event.params.to)

		token.owner    = to.id
		token.approval = fetchAccount(Address.zero()).id // implicit approval reset on transfer

		contract.save()
		token.save()

		let ev         = new ERC721Transfer(events.id(event))
		ev.emitter     = contract.id
		ev.transaction = transactions.log(event).id
		ev.timestamp   = event.block.timestamp
		ev.contract    = contract.id
		ev.token       = token.id
		ev.from        = from.id
		ev.to          = to.id
		ev.save()
+		let foobar = contract.tokens;
	}
}
```

Now deploy according to instructions in README.md.

**Comment by Amxx** [comment]
Hello @the-emerald 

You are trying to access a field that is resolved by derivation.

This is not supported by Thegraph. It's not an issue with the subgraphs, but with the core indexing software.

Also note that if this was possible, it would potentially contain thousands or even millions of entries... which would be terrible for indexing performance.

I'm not sure what you are trying to achieve, but I would recommend you find a different pattern for it.

**Comment by the-emerald** [comment]
Oh, derived fields can't be accessed from the handlers! This function handles the baseURI of a ERC-721 contract being updated, so it needs to go and update every token's URI.

**Comment by Amxx** [comment]
To be clear this should not be the case of all fields.

Given the schema

```

{
  "name": "ERC721Contract",
  "immutable": true,
  "fields": [
    { "name": "id",                      "type": "Bytes!"                                 },
    { "name": "asAccount",               "type": "Account!"                               },
    { "name": "supportsMetadata",        "type": "Boolean"                                },
    { "name": "name",                    "type": "String"                                 },
    { "name": "symbol",                  "type": "String"                                 },
    { "name": "tokens",                  "type": "ERC721Token!",    "derived": "contract" },
    { "name": "operators",               "type": "ERC721Operator!", "derived": "contract" },
    { "name": "transfers",               "type": "ERC721Transfer!", "derived": "contract" }
  ]
}
```

Everything but `tokens`, `operators` and `transfers` should be accessible

**Comment by the-emerald** [comment]
Hmm. Is there a preferred way of accessing all the tokens of a contract then? I just need all of them to refresh their URI - it should be exceeding rare that an "update URI" method is called so I'm not concerned about performance.

**Comment by Amxx** [comment]
That is unfortunately not possible.
