### ISSUE TITLE
Prepare script deletes files, then throws due to empty files

### ISSUE THREAD

**Issue by RyRy79261** [OpenZeppelin/openzeppelin-subgraphs#42]
```
> @openzeppelin/subgraphs@0.1.8-5 prepublish
> rimraf artifacts build cache generated


> @openzeppelin/subgraphs@0.1.8-5 prepare
> bash scripts/prepare.sh

node:internal/modules/cjs/loader:1176
    throw err;
    ^

SyntaxError: /openzeppelin-subgraphs/configs/accesscontrol.json: Unexpected end of JSON input
```

![image](https://user-images.githubusercontent.com/10461622/196643656-9594c8dc-d9db-4511-96c8-c330497617ca.png)

**Comment by Amxx** [comment]
I think this the same error as #41. Without `jq` working, prepare was producing empty files that are not valid json.

fdc25ebf82c158916584940e564a823f89e3db1b should fix that.
