### ISSUE TITLE
Duplicate key value violates unique constraint "erc721_transfer_id_key"

### ISSUE THREAD

**Issue by hangleang** [OpenZeppelin/openzeppelin-subgraphs#52]
Hi guys, I was deployed a subgraph which's index `NFTs` (ERC721 + ERC1155) on goerli-testnet. Everything seems working fine, but until recent block, it show the following error:

```
A non-deterministic fatal error occured at block 8656060: Failed to transact block operations: store error: duplicate key value violates unique constraint "erc721_transfer_id_key"
```

I think it can cause by `event.id(block)` function, which is concatenate block number to log index.

**Comment by hangleang** [comment]
![Screenshot_20230315_102422](https://user-images.githubusercontent.com/52003343/225198912-dd90b331-7338-4218-b39f-0ffa91945858.png)

**Comment by Amxx** [comment]
hello @hangleang

This is strange, event naming should be unique. Can you check if you don't have the same datasource specified multiple time?

**Comment by hangleang** [comment]
Hi @Amxx, 

I'm sure that's not cause by any changes. I only deployed the `NFTs subgraph` from this subgraph template and define a config for `goerli-testnet`, there is nothing changes in the resolver.

**Comment by Amxx** [comment]
Closing this from inactivity. I believe this is the result of a duplicated datasource. Please re-open if still relevant.
