### ISSUE TITLE
✖ Failed to upload subgraph to IPFS: Failed to upload file to IPFS: HTTPError: Forbidden Only certain IPFS methods are allowed

### ISSUE THREAD

**Issue by jordaniza** [OpenZeppelin/openzeppelin-subgraphs#53]
When following the sample deployment, subgraph errors out when calling `npx graph deploy`

This is using the config file shown in the example

**Comment by Amxx** [comment]
You might not be using the correct version of IPFS. I remember thegraph used to not work with the latest version of ipfs.

You should check [this repo](https://github.com/graphprotocol/graph-node) and direct your questions directly to thegraph

**Comment by jordaniza** [comment]
Thanks Hadrien, will give that a whirl
