### ISSUE TITLE
Transfers don't reduce an accounts spenders approval amount (using the oz erc20 contract)

### ISSUE THREAD

**Issue by DenhamPreen** [OpenZeppelin/openzeppelin-subgraphs#57]
If an approved spender makes a transfer the accounts mapping to that spender approval amount won't reduce if the current openzeppelin template is in use without modifications. 

In this transfer handler the approval amount isn't reduced based on the transferred amount
https://github.com/OpenZeppelin/openzeppelin-subgraphs/blob/5c55b2ecc8155b62da1eccc029b881b8c4d81568/src/datasources/erc20.ts#L30

The transferFrom function updates the spenders approval but doesnt emit a new approval event
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/5ed5a86d1d22f387ce69ab4e0ace405de8bc888d/contracts/token/ERC20/ERC20.sol#L305

In order to index the approval amount this override in the erc20 implementation would need to be implemented
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/5ed5a86d1d22f387ce69ab4e0ace405de8bc888d/contracts/token/ERC20/ERC20.sol#L277

This is not an issue if you were indexing a different erc20 implementation such as the uni token which emits an approval event when a transfer is made
https://etherscan.io/address/0x1f9840a85d5aF5bf1D1762F925BDADdC4201F984#code

**Comment by Amxx** [comment]
Yes, this behavior was changed in the oz contracts a while back. Unfortunatelly, there is no clear way to identify transferFrom (and update allowances) from the events alone.
