### ISSUE TITLE
@graphprotocol/graph-ts@0.20.1

### ISSUE THREAD

**Issue by jtry** [OpenZeppelin/openzeppelin-subgraphs#8]
@graphprotocol/graph-ts@0.20.1  has been updated to @graphprotocol/graph-ts@0.22.1
A lot of syntax needs to be updated
please help!!!!!

**Comment by jtry** [comment]
@abarmat @ @spalladino

**Comment by Amxx** [comment]
This was addressed in version `1.1.0-alpha.0`
Feel free to reopen if you are experiencing any issues with this release.
